/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/docs/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as graphql from "@nestjs/graphql";
import * as apollo from "apollo-server-express";
import * as nestAccessControl from "nest-access-control";
import { GqlDefaultAuthGuard } from "../../auth/gqlDefaultAuth.guard";
import * as gqlACGuard from "../../auth/gqlAC.guard";
import * as gqlUserRoles from "../../auth/gqlUserRoles.decorator";
import * as abacUtil from "../../auth/abac.util";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import { CreateAttachmentArgs } from "./CreateAttachmentArgs";
import { UpdateAttachmentArgs } from "./UpdateAttachmentArgs";
import { DeleteAttachmentArgs } from "./DeleteAttachmentArgs";
import { AttachmentFindManyArgs } from "./AttachmentFindManyArgs";
import { AttachmentFindUniqueArgs } from "./AttachmentFindUniqueArgs";
import { Attachment } from "./Attachment";
import { Message } from "../../message/base/Message";
import { Route } from "../../route/base/Route";
import { AttachmentService } from "../attachment.service";

@graphql.Resolver(() => Attachment)
@common.UseGuards(GqlDefaultAuthGuard, gqlACGuard.GqlACGuard)
export class AttachmentResolverBase {
  constructor(
    protected readonly service: AttachmentService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}

  @graphql.Query(() => MetaQueryPayload)
  @nestAccessControl.UseRoles({
    resource: "Attachment",
    action: "read",
    possession: "any",
  })
  async _attachmentsMeta(
    @graphql.Args() args: AttachmentFindManyArgs
  ): Promise<MetaQueryPayload> {
    const results = await this.service.count({
      ...args,
      skip: undefined,
      take: undefined,
    });
    return {
      count: results,
    };
  }

  @graphql.Query(() => [Attachment])
  @nestAccessControl.UseRoles({
    resource: "Attachment",
    action: "read",
    possession: "any",
  })
  async attachments(
    @graphql.Args() args: AttachmentFindManyArgs,
    @gqlUserRoles.UserRoles() userRoles: string[]
  ): Promise<Attachment[]> {
    const permission = this.rolesBuilder.permission({
      role: userRoles,
      action: "read",
      possession: "any",
      resource: "Attachment",
    });
    const results = await this.service.findMany(args);
    return results.map((result) => permission.filter(result));
  }

  @graphql.Query(() => Attachment, { nullable: true })
  @nestAccessControl.UseRoles({
    resource: "Attachment",
    action: "read",
    possession: "own",
  })
  async attachment(
    @graphql.Args() args: AttachmentFindUniqueArgs,
    @gqlUserRoles.UserRoles() userRoles: string[]
  ): Promise<Attachment | null> {
    const permission = this.rolesBuilder.permission({
      role: userRoles,
      action: "read",
      possession: "own",
      resource: "Attachment",
    });
    const result = await this.service.findOne(args);
    if (result === null) {
      return null;
    }
    return permission.filter(result);
  }

  @graphql.Mutation(() => Attachment)
  @nestAccessControl.UseRoles({
    resource: "Attachment",
    action: "create",
    possession: "any",
  })
  async createAttachment(
    @graphql.Args() args: CreateAttachmentArgs,
    @gqlUserRoles.UserRoles() userRoles: string[]
  ): Promise<Attachment> {
    const permission = this.rolesBuilder.permission({
      role: userRoles,
      action: "create",
      possession: "any",
      resource: "Attachment",
    });
    const invalidAttributes = abacUtil.getInvalidAttributes(
      permission,
      args.data
    );
    if (invalidAttributes.length) {
      const properties = invalidAttributes
        .map((attribute: string) => JSON.stringify(attribute))
        .join(", ");
      const roles = userRoles
        .map((role: string) => JSON.stringify(role))
        .join(",");
      throw new apollo.ApolloError(
        `providing the properties: ${properties} on ${"Attachment"} creation is forbidden for roles: ${roles}`
      );
    }
    // @ts-ignore
    return await this.service.create({
      ...args,
      data: {
        ...args.data,

        message: {
          connect: args.data.message,
        },

        route: {
          connect: args.data.route,
        },
      },
    });
  }

  @graphql.Mutation(() => Attachment)
  @nestAccessControl.UseRoles({
    resource: "Attachment",
    action: "update",
    possession: "any",
  })
  async updateAttachment(
    @graphql.Args() args: UpdateAttachmentArgs,
    @gqlUserRoles.UserRoles() userRoles: string[]
  ): Promise<Attachment | null> {
    const permission = this.rolesBuilder.permission({
      role: userRoles,
      action: "update",
      possession: "any",
      resource: "Attachment",
    });
    const invalidAttributes = abacUtil.getInvalidAttributes(
      permission,
      args.data
    );
    if (invalidAttributes.length) {
      const properties = invalidAttributes
        .map((attribute: string) => JSON.stringify(attribute))
        .join(", ");
      const roles = userRoles
        .map((role: string) => JSON.stringify(role))
        .join(",");
      throw new apollo.ApolloError(
        `providing the properties: ${properties} on ${"Attachment"} update is forbidden for roles: ${roles}`
      );
    }
    try {
      // @ts-ignore
      return await this.service.update({
        ...args,
        data: {
          ...args.data,

          message: {
            connect: args.data.message,
          },

          route: {
            connect: args.data.route,
          },
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new apollo.ApolloError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.Mutation(() => Attachment)
  @nestAccessControl.UseRoles({
    resource: "Attachment",
    action: "delete",
    possession: "any",
  })
  async deleteAttachment(
    @graphql.Args() args: DeleteAttachmentArgs
  ): Promise<Attachment | null> {
    try {
      // @ts-ignore
      return await this.service.delete(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new apollo.ApolloError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.ResolveField(() => Message, { nullable: true })
  @nestAccessControl.UseRoles({
    resource: "Attachment",
    action: "read",
    possession: "any",
  })
  async message(
    @graphql.Parent() parent: Attachment,
    @gqlUserRoles.UserRoles() userRoles: string[]
  ): Promise<Message | null> {
    const permission = this.rolesBuilder.permission({
      role: userRoles,
      action: "read",
      possession: "any",
      resource: "Message",
    });
    const result = await this.service.getMessage(parent.id);

    if (!result) {
      return null;
    }
    return permission.filter(result);
  }

  @graphql.ResolveField(() => Route, { nullable: true })
  @nestAccessControl.UseRoles({
    resource: "Attachment",
    action: "read",
    possession: "any",
  })
  async route(
    @graphql.Parent() parent: Attachment,
    @gqlUserRoles.UserRoles() userRoles: string[]
  ): Promise<Route | null> {
    const permission = this.rolesBuilder.permission({
      role: userRoles,
      action: "read",
      possession: "any",
      resource: "Route",
    });
    const result = await this.service.getRoute(parent.id);

    if (!result) {
      return null;
    }
    return permission.filter(result);
  }
}
